### ISSUE TITLE
Online Confirm problems with Moodle 4.02

### ISSUE THREAD

**Issue by ggrow** [charbusch/moodle-auth_onlineconfirm#1]
I installed the latest onlineconfirm for Moodle 3 into Moodle 4.02. 

It appeared to work for a while, then the "Enrolment Methods" button disappeared under each course's Participants/Enrolment tab, so I could no longer set installed courses to use Paypal. 

When I uninstalled onlineconfirm and purged all caches, the Enrolment Methods" button returned. 

Everything works as it did before onlineconfirm. Enrolmnet requires a confirming email as usual -- which is what I am trying to eliminate because so many students do not receive it. (I suspect that some university servers block emails that mention things like passwords or have a clickable link).

**Comment by charbusch** [comment]
I have tested this on Moodle 4.0.2 and have found no problems.  This is confusing, though, as this is an authentication method and should have nothing to do with course enrollments.  It should be installed under your auth folder.

**Comment by ggrow** [comment]
You're right, this is confusing. I will try everything again, to see if I inadventently introduced another problem.

I did have the plugin installed in the auth folder. 

The problem did not show up the day I installed onlineconfirm, but later.  

The only other plugin I can recall installing and uninstalling was Boost Navigation Fumbling, which seems to have no effect with the Boost that comes with Moodle 4.

**Comment by charbusch** [comment]
If it happens again, please turn Debugging on to maximum and let me now if you see any errors on the page.

**Comment by ggrow** [comment]
The weirdness happened again: "Enrolled Users" disappeared. I clicked out of that screen and back in again, and IT REAPPEARED. 

Here are screen shots showing the missing Enrolled Users and its reappearance. 

I'm perplexed, too.  I do not know for certain this is connected with onlineconfirm. 

![Screen Shot 2022-07-24 at 1 43 58 PM](https://user-images.githubusercontent.com/47871338/180659595-12c91d14-3927-455d-967e-2bba789a478a.jpg)

![Screen Shot 2022-07-24 at 1 50 18 PM](https://user-images.githubusercontent.com/47871338/180659743-66706b79-a7dd-4bc0-8b80-cc50eb76d465.jpg)

I will copy this over to the Moodle Forum discussion.

**Comment by ggrow** [comment]
Reporting this error message in case it means anything.

I have debugging set to Developer mode. Moodle 4.02.

After filling out the form to create a new account as a new student and submitting it, I get this error message:

Notice: Undefined property: stdClass::$emailnew in /home/nr101/public_html/nr5/auth/onlineconfirm/auth.php on line 187

When I click Continue, it proceeds normally. 

When I continue and pay with Paypal, everything seems to work as it should. After Paypal, I am correctly returned to the course I enrolled in with that student account.

**Comment by charbusch** [comment]
Thanks for that, I have updated the auth.php file to fix this issue.  Please reupload this file, and then go in to Site Administration>Plugins>Aythentication>Online Confirm and update to reset the onlineconfirm auth Config Settings
