### ISSUE TITLE
Student lands on wrong page after creating new account

### ISSUE THREAD

**Issue by ggrow** [charbusch/moodle-auth_onlineconfirm#2]
Hi, please check this.

I'm running onlineconfirm on Moodle 4.02.

My students enroll by clicking on the name of their course in an external page that is linked to the URL of that course in Moodle. 

That click takes new students to the login form with Create New Account at the bottom of it. 

After students fill out this form to create a new account and submits it, they are not taken to the course whose URL they clicked on. They are instead taken to a home page with a list of all courses. Because there are as many as 50 courses, they can easily click on the wrong course at this point, get sent to Paypal, and return enrolled in the wrong course. 

This is different from how onlineconfirm behaved in Moodle 3. I think there might be an error here. 

Could you modify onlineconfirm so that, at this point, students who reached the Create a New Account form by clicking on a course URL, find themselves back at that course URL (1) after they click to submit the New Account form, and (2) when Paypal returns them after payment to enroll. 

When is disable onlineconfirm and use email-based self-registration, students are taken to the course URL, and Paypal returns them to the course URL as exected. 

If this does not make sense, ask me and I'll try to clarify.

Thanks.

**Comment by charbusch** [comment]
I have modified the auth file to redirect to what is called the session wantsurl instead of always redirecting to wwwroot.  Please test this.

**Comment by ggrow** [comment]
That works!

After enrolling through Paypal, the student now lands on the URL of the course she chose to get to this point. 

You have been wonderful and responsive. Thank you so much!

Onlineconfirm helps with one of the most common problems I have had using Moodle: Students do not receive the confirmation email because they do not know where to look, or because the email server blocks it, or whatever.  

I hope my reports have been helpful.

Gerald

**Comment by charbusch** [comment]
Great, glad it helps.  Thanks for the report, returning to the previous url is just not something I had thought about since my clients do not want that.
